import type { LLMCompleteInput, LLMCompleteOutput, LLMProvider } from "@coding-agent/shared";
import { CODING_AGENT_PLAN_PROMPT, PATCH_GENERATION_PROMPT } from "./prompts.js";

/**
 * Deterministic provider for running the whole loop with no API key.
 * - Plan requests -> a valid plan JSON derived from the task.
 * - Patch requests -> a unified diff creating a new AGENT_NOTES.md (always
 *   applies cleanly, so the approval/apply/rollback flow is fully exercisable).
 */
export class MockLLMProvider implements LLMProvider {
  readonly name = "mock";

  async complete(input: LLMCompleteInput): Promise<LLMCompleteOutput> {
    const system = input.messages.find((m) => m.role === "system")?.content ?? "";
    const task = input.messages.find((m) => m.role === "user")?.content ?? "";

    if (system.startsWith(CODING_AGENT_PLAN_PROMPT.slice(0, 24))) {
      return { text: this.plan(task) };
    }
    if (system.startsWith(PATCH_GENERATION_PROMPT.slice(0, 24))) {
      return { text: this.patch(task) };
    }
    return { text: "" };
  }

  private plan(task: string): string {
    const queries = extractKeywords(task);
    return JSON.stringify(
      {
        summary: `Mock plan for task: ${firstLine(task)}`,
        searchQueries: queries,
        likelyFiles: [],
        suggestedCommands: [],
      },
      null,
      2,
    );
  }

  private patch(task: string): string {
    const summary = firstLine(task).replace(/\r?\n/g, " ");
    const body = [
      "# Agent Notes",
      "",
      `Task: ${summary}`,
      "",
      "Generated by MockLLMProvider for end-to-end testing.",
    ];
    const lines = body.map((l) => `+${l}`).join("\n");
    return [
      "--- /dev/null",
      "+++ b/AGENT_NOTES.md",
      `@@ -0,0 +1,${body.length} @@`,
      lines,
      "",
    ].join("\n");
  }
}

function firstLine(text: string): string {
  return (text.split("\n")[0] ?? "").trim().slice(0, 120) || "(empty task)";
}

function extractKeywords(task: string): string[] {
  const ids = task.match(/[A-Za-z_][A-Za-z0-9_]{2,}/g) ?? [];
  const stop = new Set(["the", "and", "for", "this", "that", "with", "function", "添加", "修复"]);
  const unique = [...new Set(ids)].filter((w) => !stop.has(w.toLowerCase()));
  return unique.slice(0, 5);
}
